### ISSUE TITLE
Install problem/question

### ISSUE THREAD

**Issue by grbs27** [AlexTISYoung/SNIPar#34]
Hi there,

I have been attempting to install snipar on my university's hpc. I have used conda to install 
`conda create -n sniparenv python=3.9 scipy`
`conda activate sniparenv`
`pip install snipar`

Things appear to install fine without error but when I run the test:
`python -m unittest snipar.tests` 
it starts okay and runs from "snipar.tests.test_example.TestExample.test_example" to "snipar.tests.test_sibreg.test_regrnd_functions.test_likelihood" and then errors out with the following message:

>.snipar.tests.test_sibreg.test_regrnd_functions.test_likelihood: 49.296
.
======================================================================
ERROR: test_example (snipar.tests.test_example.TestExample)
----------------------------------------------------------------------
>Traceback (most recent call last):
  File "/users/8/saund247/.local/lib/python3.9/site-packages/snipar/tests/test_example.py", line 27, in test_example
    subprocess.run(c.split(), stdout=stdout)
  File "/users/8/saund247/.conda/envs/sniparenv/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/users/8/saund247/.conda/envs/sniparenv/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/users/8/saund247/.conda/envs/sniparenv/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ibd.py'

----------------------------------------------------------------------
>Ran 28 tests in 176.232s

>FAILED (errors=1)

I have tried several different install methods but can't seem to figure this out. Do you have any ideas what I might be doing wrong here? 

Thanks so much!
Gretchen

**Comment by grbs27** [comment]
Apologies - figured out the install problem!
